#pragma config(Sensor, S1,     DFront,         sensorSONAR)
#pragma config(Sensor, S2,     DBack,          sensorSONAR)
#pragma config(Sensor, S3,     DLeft,          sensorSONAR)
#pragma config(Sensor, S4,     DRight,         sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "JoystickDriver.c"
#include "libs/teleoputils.h"

void initializeRobot()
{

	return;
}

float getAngle(int x, int y) {
	return atan2(x,y);
}
int getMagnitude(int x, int y) {
	return sqrt(x*x + y*y);
}

float angle = 0;
int magnitude = 0;
float w1angle = 0;
float w2angle = 2*PI/3;
float w3angle = 4*PI/3;

float sensorAngle[4] = { //Target Angles
  0,			//Go Backward
  PI,  // Go Forward
	PI/2,  // Go Right
	3*PI/2 // Go Left
};
int sensorDist[4] = {0,0,0,0};

int mA, mB, mC;

task main() {

	magnitude = 100;
	initializeRobot();

	//waitForStart();   // wait for start of tele-op phase

	while (true) {
		sensorDist[0] = SensorValue[DFront];
		sensorDist[1] = SensorValue[DBack];
    sensorDist[2] = SensorValue[DLeft];
    sensorDist[3] = SensorValue[DRight];

    for (int i = 0; i < 4; i++) {
    	if (sensorDist[i] < 26 && sensorDist[i]!=0) {
    		//PlayTone(440 + 200*i, 1);
        angle = sensorAngle[i];
    		angle = angle + (random[45] - 22) * PI / 180; // Random variation

    	}
  	}

		mA = magnitude*sin(angle + w1angle);
		mB = magnitude*sin(angle + w2angle);
		mC = magnitude*sin(angle + w3angle);

		motor[motorA] = mA;
		motor[motorB] = mB;
		motor[motorC] = mC;
		wait1Msec(20);
		angle = angle - 0.005;
	}
}
